flaskdepot/search/models.py
__author__ = 'Gebruiker'

flaskDepot/views/file.py
import os
from flask.ext.login import current_user, login_required
from sqlalchemy import func
from werkzeug.exceptions import NotAcceptable, abort
from werkzeug.utils import secure_filename
from flask import render_template, flash, url_for
from slugify import slugify
from flaskdepot import app, db
from flaskdepot.controllers.file import UploadForm, EvaluationForm
from flaskdepot.models import File, BroadCategory, NarrowCategory, Comment, Vote


@app.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    form.broad_category.choices = [(cat.id, cat.name) for cat in BroadCategory.query.order_by('name')]
    form.narrow_category.choices = [(cat.id, cat.name) for cat in NarrowCategory.query.order_by('name')]

    if form.validate_on_submit():
        new_file = File()
        new_file.name = form.filename.data
        new_file.slug = slugify(form.filename.data)
        new_file.file_name = secure_filename(form.package.data.filename)
        new_file.preview1_name = secure_filename(form.image_1.data.filename)
        new_file.preview2_name = secure_filename(form.image_2.data.filename) or None
        new_file.description = form.description.data
        new_file.version = form.version.data
        new_file.broad_category_id = form.broad_category.data
        new_file.narrow_category_id = form.narrow_category.data
        new_file.author_id = current_user.id

        package = form.package.data
        package.save(os.path.join(app.config['FILE_DIR'], secure_filename(package.filename)))

        prev1 = form.image_1.data
        prev1.save(os.path.join(app.config['PREVIEW_DIR'], secure_filename(prev1.filename)))

        if len(form.image_2.data.filename) is not 0:
            prev2 = form.image_2.data
            prev2.save(os.path.join(app.config['PREVIEW_DIR'], secure_filename(prev2.filename)))

        db.session.add(new_file)
        db.session.commit()

        flash('File has been uploaded')

    return render_template('upload.html', form=form, title="Upload")


@app.route('/file/<fileid>/<slug>/', methods=['GET', 'POST'])
@app.route('/file/<fileid>/', methods=['GET', 'POST'])
def file_one(fileid, slug=None):
    form = EvaluationForm()

    if form.validate_on_submit():
        if form.comment.data:
            comment = Comment()
            comment.text = form.comment.data
            comment.user_id = current_user.id
            comment.file_id = fileid
            db.session.add(comment)
            db.session.commit()
            flash(u'Your comment has been added', 'success')
    if form.rating.data:
        vote = Vote.query.filter_by(file_id=fileid, user_id=current_user.id).first()
        if not vote:
            vote = Vote()
            vote.value = form.rating.data
            vote.file_id = fileid
            vote.user_id = current_user.id
            db.session.add(vote)
            db.session.commit()
            flash(u'Your rating has been added', 'success')
        else:
            flash(u'You have already voted for this file', 'alert')

    _file = File.query.filter_by(id=fileid).first()

    if not _file:
        abort(404)

    allow_rating = not current_user.is_anonymous() and (Vote.query.filter_by(file_id=fileid, user_id=current_user.id).first() is None)
    num_rating = db.session.query(func.count(Vote.id)).filter_by(file_id=fileid).scalar()
    avg_rating = db.session.query(func.avg(Vote.value)).filter_by(file_id=fileid).scalar()

    return render_template('file.html',
                           upload=_file,
                           form=form,
                           allow_rating=allow_rating,
                           num_rating=num_rating,
                           avg_rating=avg_rating,
                           title=u'{0} by {1}'.format(_file.name, _file.author.username))


@app.route('/file/all/', methods=['GET'])
@login_required
def file_all():
    files = File.query.all()
    ret = ''
    for afile in files:
        ret += u'{0} by {1}<br>'.format(afile.name, afile.author.username)
    return ret

flaskdepot/admin/controllers.py
from flask_wtf.file import FileField, FileAllowed
from wtforms import SelectField, TextField, Form, TextAreaField, RadioField, BooleanField
from wtforms.validators import Required
from flaskdepot.base.controllers import RedirectForm
from flaskdepot.file.models import File
from flaskdepot.user.models import User


class AdminAccountEditForm(RedirectForm):
    group = SelectField('User Group', coerce=int)
    username = TextField('Username')

    def validate(self):
        validate = Form.validate(self)

        if self.username.data:
            user = User.query.filter_by(username=self.username.data).first()
            if user:
                self.username.errors.append('An account already exists with that username')
                validate = False

        return validate


class AdminFileEditForm(RedirectForm):
    fileid = -1
    filename = TextField('Filename', validators=[
        Required("Please enter a file name.")]
    )

    package = FileField('File', validators=[
        FileAllowed(['zip', 'rar'], message="You can only upload compressed (.zip, .rar) files.")])

    image_1 = FileField('Preview 1', validators=[
        FileAllowed(['png', 'jpg', 'gif'], message="You can only upload image (.png, .jpg, .gif) files.")
    ])

    image_2 = FileField('Preview 2', validators=[
        FileAllowed(['png', 'jpg', 'gif'], message="You can only upload image (.png, .jpg, .gif) files.")
    ])

    version = TextField('Version', default='1.0')

    description = TextAreaField('Description', validators=[
        Required("Please enter a description for your file.")
    ])

    broad_category = SelectField('Broad Category', coerce=int, validators=[
        Required("Please enter a broad category for your file.")
    ])

    narrow_category = SelectField('Narrow Category', coerce=int, validators=[
        Required("Please enter a narrow category for your file")
    ])

    def validate(self):
        validate = Form.validate(self)

        if self.filename.data:
            other_file = File.query.filter_by(name=self.filename.data).first()
            if other_file and other_file.id != int(self.fileid):
                self.filename.errors.append('A file with this name already exists.')
                validate = False

        return validate


class AdminAddCategoryForm(RedirectForm):
    name = TextField('Name', validators=[
        Required("Please enter a category name")
    ])

    description = TextAreaField('Description')

    type = RadioField('Type', choices=[('broad', 'Broad Category'), ('narrow', 'Narrow Category')])


class AdminAddUsergroupForm(RedirectForm):
    name = TextField('Name', validators=[
        Required("Please enter a usergroup name")
    ])
    is_default = BooleanField('Default', default=False)
    is_banned = BooleanField('Banned', default=False)
    is_admin = BooleanField('Admin', default=False)
    is_uploader = BooleanField('Uploader', default=False)


class AdminRenameUsergroupForm(RedirectForm):
    name = TextField('Name', validators=[
        Required("Please enter a category name")
    ])


class AdminRenameCategoryForm(RedirectForm):
    name = TextField('Name', validators=[
        Required("Please enter a category name")
    ])
    catid = -1
    type = None


class AdminDescribeCategoryForm(RedirectForm):
    description = TextAreaField('Description')
    catid = -1
    type = None

flaskdepot/app.py
from flask import Flask, render_template
from flaskdepot.extensions import db, login_manager, mail, migrate, bcrypt
from flaskdepot.utils.helper import url_for


def configure_blueprints(app):
    """
    Configures the blueprints
    """

    from flaskdepot.user.views import user
    from flaskdepot.base.views import base
    from flaskdepot.admin.views import admin
    from flaskdepot.file.views import file
    from flaskdepot.search.views import search

    app.register_blueprint(file, url_prefix=app.config["FILE_PREFIX"])
    app.register_blueprint(user, url_prefix=app.config["USER_PREFIX"])
    app.register_blueprint(search, url_prefix=app.config["SEARCH_PREFIX"])
    app.register_blueprint(admin, url_prefix=app.config["ADMIN_PREFIX"])
    app.register_blueprint(base)



def configure_extensions(app):
    """
    Configures the Flask extensions
    """
    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    bcrypt.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        """
        Loads the current user for Flask-Login
        """
        from flaskdepot.user.models import User
        return db.session.query(User).filter_by(active=True, id=user_id).first()
    login_manager.init_app(app)


def configure_filters(app):
    # Use custom url_for that supports runtime parameters
    app.jinja_env.globals['url_for'] = url_for


def configure_handlers(app):
    @app.errorhandler(401)
    def unauthorized(e):
        return render_template("error.html", name=u'Unauthorized',
                               message=u'Sorry, but you need to log in to access this page'), 401


    @app.errorhandler(403)
    def forbidden(e):
        return render_template("error.html", name=u'Forbidden',
                               message=u'Sorry, but you do not have access to this page'), 403


    @app.errorhandler(404)
    def page_not_found(e):
        return render_template("error.html", name=u'Not Found',
                               message=u'Sorry, the page you were looking for could not be found'), 404


    @app.errorhandler(410)
    def gone(e):
        return render_template("error.html", name=u'Gone',
                               message=u'Sorry, the page you were looking for is not accessible'), 410


    @app.errorhandler(500)
    def internal_server_error(e):
        return render_template("error.html", name=u'Server Error',
                               message=u'Sorry, the server encountered an error while processing your request.'
                                       u' Please try again later.'
                                       u' If this problem persists, contact the administration'), 500


def configure_requests(app):
    pass


def configure_jinja(app):
    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True


def create_app(config=None):
    """
    Creates the application
    """
    app = Flask("flaskdepot")

    # Default configuration
    app.config.from_object('flaskdepot.configs.default.DefaultConfig')
    # Update the configuration if it exists in the parameters
    app.config.from_object(config)
    # Update the configuration based on environment variables
    app.config.from_envvar("FLASKDEPOT_CONFIG", silent=True)

    configure_blueprints(app)
    configure_extensions(app)
    configure_filters(app)
    configure_handlers(app)
    configure_jinja(app)
    configure_requests(app)

    return app

flaskdepot/base/__init__.py
__author__ = 'Gebruiker'

flaskdepot/base/controllers.py
from flask import request, redirect, url_for, send_from_directory
from flask_wtf import Form
from wtforms import HiddenField
from urlparse import urlparse, urljoin


def get_redirect_target():
    for target in request.args.get('next'), request.referrer:
        if not target:
            continue
        if is_safe_url(target):
            return target


def is_safe_url(target):
    if target == '':
        return False
    if target[0] == '/':
        return True
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and \
        ref_url.netloc == test_url.netloc


class RedirectForm(Form):
    next = HiddenField()

    def __init__(self, *args, **kwargs):
        Form.__init__(self, *args, **kwargs)
        if not self.next.data:
            self.next.data = get_redirect_target() or ''

    def redirect(self, endpoint='index', url=None, **values):
        if is_safe_url(self.next.data):
            return redirect(self.next.data)
        target = get_redirect_target() or url
        return redirect(target or url_for(endpoint, **values), code=303)

flaskdepot/base/views.py
from flask import Blueprint, render_template
from flaskdepot.file.models import File, Comment

base = Blueprint("base", __name__)


@base.route('/')
@base.route('/index/', methods=['GET'])
def index():
    files = File.query.order_by(File.created_on).limit(3).all()
    comments = Comment.query.order_by(Comment.id).limit(10).all()
    return render_template('index.html', files=files, comments=comments, title='Index')

flaskdepot/configs/__init__.py
__author__ = 'Gebruiker'

flaskdepot/file/__init__.py
__author__ = 'Gebruiker'

flaskdepot/search/__init__.py
__author__ = 'Gebruiker'

flaskdepot/search/controllers.py
from wtforms import TextField, BooleanField, SelectField
from flaskdepot.base.controllers import RedirectForm


class SearchForm(RedirectForm):
    keyword = TextField('Keyword')
    author = SelectField('File author', default=[])
    broad_category = SelectField('Broad category', default=[])
    narrow_category = SelectField('Narrow category', default=[])
    exclude_locked = BooleanField('Exclude locked files', default=True)

flaskdepot/user/views.py
import datetime
from flask import render_template, request, flash, url_for, redirect, Blueprint, abort
from flask_login import login_user, login_required, current_user, logout_user
from flaskdepot.extensions import db
from flaskdepot.user.models import User, Usergroup
from flaskdepot.user.controllers import RegistrationForm, LoginForm, AccountEditForm, AccountDeleteForm

user = Blueprint("user", __name__)


@user.route('/register/', methods=['GET', 'POST'])
def register():

    if current_user.is_authenticated():
        return redirect(url_for('base.index'))

    form = RegistrationForm()
    form.next.data = url_for('base.index')

    if form.validate_on_submit():
        user = User()
        user.username = form.username.data
        user.set_password(form.password.data)
        user.email = form.email.data
        user.created_ip = request.remote_addr
        user.group = Usergroup.query.filter_by(is_default=True).first()

        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash(u'Thank you for signing up! You are now logged in as {0}'.format(user.username))

        return form.redirect()
    else:
        return render_template('user/register.html', form=form, title=u'Registration')


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    form.next.data = url_for('base.index')

    if form.validate_on_submit():
        if not form.remember.data:
            login_user(form.user)
            form.user.last_active_ip = request.remote_addr
            form.user.last_active_on = datetime.datetime.now()
            db.session.commit()
        else:
            login_user(form.user, remember=form.remember.data)

        flash(u'You have been logged in as {0}'.format(form.user.username))
        return form.redirect()
    else:
        return render_template('user/login.html', form=form, title=u'Log in')


@user.route('/logout/', methods=['GET'])
@login_required
def logout():
    logout_user()
    flash(u'You have been logged out')
    return redirect(url_for('base.index'))


# User Profile
@user.route('/<id>/', methods=['GET'])
@login_required
def user_one(id):
    if current_user.group.is_admin or current_user.id == int(id):
        _user = User.query.filter_by(id=id).first()
        return render_template('user/profile.html', user=_user, title=u"Profile for {0}".format(_user.username))
    else:
        return 'You cannot access this page'


@user.route('/<id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_user(id):
    if current_user.group.is_admin or current_user.id == int(id):
        _user = User.query.filter_by(id=id).first()
        form = AccountEditForm()

        if form.validate_on_submit():
            if form.email.data:
                _user.email = form.email.data
                flash('The e-mail address has been updated')
            if form.password.data and (form.password.data == form.confirm_password.data):
                _user.set_password(form.password.data)
                flash('The password has been updated')
            db.session.commit()

        return render_template('user/edit.html', form=form, title=u"Edit profile for {0}".format(_user.username), user=_user)
    else:
        abort(403)


@user.route('/<id>/delete/', methods=['GET', 'POST'])
@login_required
def delete_user(id):
    if not current_user.group.is_admin:
        abort(403)
    else:
        _user = User.query.filter_by(id=id).first()
        form = AccountDeleteForm()
        form.next.data = url_for('.user_one', id=id)

        if form.validate_on_submit():
            if _user.username == form.username.data:
                _user.active = False
                db.session.commit()
            else:
                form.username.errors.append('Please enter the correct username')
                form.redirect()
        else:
            return render_template('user/delete.html', form=form,
                                   title=u"Delete account for {0}".format(_user.username), user=_user)


@user.route('/me/', methods=['GET'])
@login_required
def user_me():
    return redirect(url_for('user.user_one', id=current_user.id))

flaskdepot/templates/user/delete.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'upload' %}

{% block content %}
    <div class="panel clearfix">
        <form method="post">
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="large-12 columns">
                    {% if not current_user.group.is_admin %}
                        <p>For security, please enter your current username before deleting your account.
                            Deleting an account <strong>cannot be undone</strong>!</p>
                    {% else %}
                        <p>For security, please enter the username that you want to delete. Deleting an
                            account <strong>cannot be undone</strong>!</p>
                    {% endif %}
                </div>
            </div>

            {{ render_field(form.username, placeholder=user.username) }}
            <div class="row">
                <div class="large-12 columns">
                    <input type="submit" value="Delete" class="button">
                </div>
            </div>
        </form>
        {{ flashes() }}
    </div>
{% endblock %}

flaskdepot/templates/user/edit.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'upload' %}

{% block content %}
    <div class="panel clearfix">
        <form method="post">
            {{ form.hidden_tag() }}
            {{ render_field(form.email, placeholder=user.email) }}
            {{ render_field(form.password) }}
            {{ render_field(form.confirm_password) }}
            <div class="row">
                <div class="large-12 columns">
                    <input type="submit" value="Edit" class="button">
                </div>
            </div>
        </form>
        {{ flashes() }}
    </div>
{% endblock %}

flaskdepot/templates/user/login.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'login' %}

{% block content %}
    <div class="panel clearfix">
        <form method="post">
            {{ form.hidden_tag() }}
            {{ render_field(form.username) }}
            {{ render_field(form.password) }}
            {{ render_field(form.remember) }}
            <div class="row">
                <div class="large-12 columns">
                    <input type="submit" value="Log in" class="button">
                </div>
            </div>
        </form>
        {{ flashes() }}
    </div>
{% endblock %}

flaskdepot/templates/user/profile.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_info %}
{% set activepage = 'profile' %}

{% block content %}
    <div class="panel clearfix">
        <fieldset>
            <legend>Your account</legend>
            {{ render_info('Username', user.username) }}
            {{ render_info('Group', user.group.name) }}
            {{ render_info('Account created', user.created_on) }}
            {{ render_info('E-mail', user.email) }}

            <div class="row margin-top">
                <div class="large-8 large-centered column text-center">
                    <a href="{{ url_for('user.edit_user', id=user.id) }}" class="button success">Edit profile</a>
                    {% if current_user.group.is_admin %}
                        <a href="{{ url_for('admin.edit_user', id=user.id) }}" class="button">Edit account</a>
                        <a href="{{ url_for('user.delete_user', id=user.id) }}" class="button alert">Delete account</a>
                    {% endif %}
                </div>
            </div>
        </fieldset>
    </div>
{% endblock %}

flaskdepot/templates/user/register.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'register' %}

{% block content %}
<div class="panel clearfix">
    <form method="post">
        {{ form.hidden_tag() }}
        {{ render_field(form.username) }}
        {{ render_field(form.email) }}
        {{ render_field(form.confirm_email) }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        <div class="row">
            <div class="large-12 columns">
                <input type="submit" value="Register" class="button">
            </div>
        </div>
    </form>
    {{ flashes() }}
</div>
{% endblock %}