flaskdepot/search/models.py
__author__ = 'Gebruiker'

flaskDepot/views/file.py
import os
from flask.ext.login import current_user, login_required
from sqlalchemy import func
from werkzeug.exceptions import NotAcceptable, abort
from werkzeug.utils import secure_filename
from flask import render_template, flash, url_for
from slugify import slugify
from flaskdepot import app, db
from flaskdepot.controllers.file import UploadForm, EvaluationForm
from flaskdepot.models import File, BroadCategory, NarrowCategory, Comment, Vote


@app.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    form.broad_category.choices = [(cat.id, cat.name) for cat in BroadCategory.query.order_by('name')]
    form.narrow_category.choices = [(cat.id, cat.name) for cat in NarrowCategory.query.order_by('name')]

    if form.validate_on_submit():
        new_file = File()
        new_file.name = form.filename.data
        new_file.slug = slugify(form.filename.data)
        new_file.file_name = secure_filename(form.package.data.filename)
        new_file.preview1_name = secure_filename(form.image_1.data.filename)
        new_file.preview2_name = secure_filename(form.image_2.data.filename) or None
        new_file.description = form.description.data
        new_file.version = form.version.data
        new_file.broad_category_id = form.broad_category.data
        new_file.narrow_category_id = form.narrow_category.data
        new_file.author_id = current_user.id

        package = form.package.data
        package.save(os.path.join(app.config['FILE_DIR'], secure_filename(package.filename)))

        prev1 = form.image_1.data
        prev1.save(os.path.join(app.config['PREVIEW_DIR'], secure_filename(prev1.filename)))

        if len(form.image_2.data.filename) is not 0:
            prev2 = form.image_2.data
            prev2.save(os.path.join(app.config['PREVIEW_DIR'], secure_filename(prev2.filename)))

        db.session.add(new_file)
        db.session.commit()

        flash('File has been uploaded')

    return render_template('upload.html', form=form, title="Upload")


@app.route('/file/<fileid>/<slug>/', methods=['GET', 'POST'])
@app.route('/file/<fileid>/', methods=['GET', 'POST'])
def file_one(fileid, slug=None):
    form = EvaluationForm()

    if form.validate_on_submit():
        if form.comment.data:
            comment = Comment()
            comment.text = form.comment.data
            comment.user_id = current_user.id
            comment.file_id = fileid
            db.session.add(comment)
            db.session.commit()
            flash(u'Your comment has been added', 'success')
    if form.rating.data:
        vote = Vote.query.filter_by(file_id=fileid, user_id=current_user.id).first()
        if not vote:
            vote = Vote()
            vote.value = form.rating.data
            vote.file_id = fileid
            vote.user_id = current_user.id
            db.session.add(vote)
            db.session.commit()
            flash(u'Your rating has been added', 'success')
        else:
            flash(u'You have already voted for this file', 'alert')

    _file = File.query.filter_by(id=fileid).first()

    if not _file:
        abort(404)

    allow_rating = not current_user.is_anonymous() and (Vote.query.filter_by(file_id=fileid, user_id=current_user.id).first() is None)
    num_rating = db.session.query(func.count(Vote.id)).filter_by(file_id=fileid).scalar()
    avg_rating = db.session.query(func.avg(Vote.value)).filter_by(file_id=fileid).scalar()

    return render_template('file.html',
                           upload=_file,
                           form=form,
                           allow_rating=allow_rating,
                           num_rating=num_rating,
                           avg_rating=avg_rating,
                           title=u'{0} by {1}'.format(_file.name, _file.author.username))


@app.route('/file/all/', methods=['GET'])
@login_required
def file_all():
    files = File.query.all()
    ret = ''
    for afile in files:
        ret += u'{0} by {1}<br>'.format(afile.name, afile.author.username)
    return ret

flaskdepot/admin/controllers.py
from flask_wtf.file import FileField, FileAllowed
from wtforms import SelectField, TextField, Form, TextAreaField, RadioField, BooleanField
from wtforms.validators import Required
from flaskdepot.base.controllers import RedirectForm
from flaskdepot.file.models import File
from flaskdepot.user.models import User


class AdminAccountEditForm(RedirectForm):
    group = SelectField('User Group', coerce=int)
    username = TextField('Username')

    def validate(self):
        validate = Form.validate(self)

        if self.username.data:
            user = User.query.filter_by(username=self.username.data).first()
            if user:
                self.username.errors.append('An account already exists with that username')
                validate = False

        return validate


class AdminFileEditForm(RedirectForm):
    fileid = -1
    filename = TextField('Filename', validators=[
        Required("Please enter a file name.")]
    )

    package = FileField('File', validators=[
        FileAllowed(['zip', 'rar'], message="You can only upload compressed (.zip, .rar) files.")])

    image_1 = FileField('Preview 1', validators=[
        FileAllowed(['png', 'jpg', 'gif'], message="You can only upload image (.png, .jpg, .gif) files.")
    ])

    image_2 = FileField('Preview 2', validators=[
        FileAllowed(['png', 'jpg', 'gif'], message="You can only upload image (.png, .jpg, .gif) files.")
    ])

    version = TextField('Version', default='1.0')

    description = TextAreaField('Description', validators=[
        Required("Please enter a description for your file.")
    ])

    broad_category = SelectField('Broad Category', coerce=int, validators=[
        Required("Please enter a broad category for your file.")
    ])

    narrow_category = SelectField('Narrow Category', coerce=int, validators=[
        Required("Please enter a narrow category for your file")
    ])

    def validate(self):
        validate = Form.validate(self)

        if self.filename.data:
            other_file = File.query.filter_by(name=self.filename.data).first()
            if other_file and other_file.id != int(self.fileid):
                self.filename.errors.append('A file with this name already exists.')
                validate = False

        return validate


class AdminAddCategoryForm(RedirectForm):
    name = TextField('Name', validators=[
        Required("Please enter a category name")
    ])

    description = TextAreaField('Description')

    type = RadioField('Type', choices=[('broad', 'Broad Category'), ('narrow', 'Narrow Category')])


class AdminAddUsergroupForm(RedirectForm):
    name = TextField('Name', validators=[
        Required("Please enter a usergroup name")
    ])
    is_default = BooleanField('Default', default=False)
    is_banned = BooleanField('Banned', default=False)
    is_admin = BooleanField('Admin', default=False)
    is_uploader = BooleanField('Uploader', default=False)


class AdminRenameUsergroupForm(RedirectForm):
    name = TextField('Name', validators=[
        Required("Please enter a category name")
    ])


class AdminRenameCategoryForm(RedirectForm):
    name = TextField('Name', validators=[
        Required("Please enter a category name")
    ])
    catid = -1
    type = None


class AdminDescribeCategoryForm(RedirectForm):
    description = TextAreaField('Description')
    catid = -1
    type = None

flaskdepot/admin/views.py
import os
from flask import Blueprint, abort, flash, render_template, current_app, request, url_for
from flask.ext.login import login_required, current_user
from slugify import slugify
from sqlalchemy import func
from werkzeug.exceptions import BadRequest
from werkzeug.utils import secure_filename, redirect
from flaskdepot.admin.controllers import AdminAccountEditForm, AdminFileEditForm, AdminAddCategoryForm, \
    AdminRenameCategoryForm, AdminDescribeCategoryForm, AdminAddUsergroupForm, AdminRenameUsergroupForm
from flaskdepot.extensions import db
from flaskdepot.file.models import Download, File, Vote, Comment, BroadCategory, NarrowCategory
from flaskdepot.user.models import User, Usergroup
from flaskdepot.utils.helper import likeable

admin = Blueprint("admin", __name__)


@admin.before_request
def check_admin():
    if not current_user.group.is_admin:
        abort(403)


@admin.route('/index', methods=['GET'])
@login_required
def index():
    stats = list()
    stats.append({
        'name': 'Downloads',
        'result': db.session.query(func.count(Download.id)).scalar()
    })
    stats.append({
        'name': 'Files',
        'result': db.session.query(func.count(File.id)).scalar()
    })
    stats.append({
        'name': 'Users',
        'result': db.session.query(func.count(User.id)).scalar()
    })
    stats.append({
        'name': 'Votes',
        'result': db.session.query(func.count(Vote.id)).scalar()
    })
    stats.append({
        'name': 'Comments',
        'result': db.session.query(func.count(Comment.id)).scalar()
    })

    return render_template('admin/index.html', stats=stats, title="Administration")


@admin.route('/user', methods=['GET'])
@admin.route('/user/page-<int:page>', methods=['GET'])
@login_required
def user(page=1):
    users = User.query
    _username = request.args.get('username')
    _email = request.args.get('email')
    _usergroup = request.args.get('usergroup')

    if _username and len(_username) > 0:
        users = users.filter(User.username.ilike(likeable(_username)))
    if _email and len(_email) > 0:
        users = users.filter(User.email.ilike(likeable(_email)))
    if _usergroup and len(_usergroup) > 0:
        users = users.filter(User.group_id.is_(_usergroup))

    users = users.paginate(page, current_app.config['RESULTS_PER_PAGE'], False)
    usergroups = Usergroup.query.all()
    return render_template('admin/user.html', users=users, usergroups=usergroups, title="User administration")


@admin.route('/file', methods=['GET'])
@admin.route('/file/page-<int:page>', methods=['GET'])
@login_required
def file(page=1):
    files = File.query
    _filename = request.args.get('filename')
    _author = request.args.get('author')

    if _filename and len(_filename) > 0:
        files = files.filter(File.file_name.ilike(likeable(_filename)))
    if _author and len(_author) > 0:
        files = files.filter(File.author_id.is_(_author))

    files = files.paginate(page, current_app.config['RESULTS_PER_PAGE'], False)
    users = db.session.query(User)\
        .join(Usergroup)\
        .filter(Usergroup.is_uploader)\
        .filter(User.group_id == Usergroup.id)\
        .all()
    return render_template('admin/file.html', files=files, users=users, title="File administration")


@admin.route('/usergroup', methods=['GET', 'POST'])
@login_required
def usergroup():
    groups = Usergroup.query.all()
    form = AdminAddUsergroupForm()
    form.next.data = url_for('admin.usergroup')

    if form.validate_on_submit():
        group = Usergroup()
        group.name = form.name.data
        group.is_banned = form.is_banned.data
        group.is_default = form.is_default.data
        group.is_admin = form.is_admin.data
        group.is_uploader = form.is_uploader.data

        db.session.add(group)
        db.session.commit()
        flash('Usergroup has been added')

        return form.redirect()

    return render_template('admin/usergroup.html', groups=groups, form=form, title="Usergroup administration")


@admin.route('/usergroup/<groupid>/switch', methods=['GET'])
@login_required
def switch_usergroup(groupid):
    group = Usergroup.query.filter_by(id=groupid).first_or_404()
    _type = request.args.get('type')

    if _type == 'banned':
        group.is_banned = False if group.is_banned else True
    elif _type == 'default':
        group.is_default = False if group.is_default else True
    elif _type == 'admin':
        group.is_admin = False if group.is_admin else True
    elif _type == 'uploader':
        group.is_uploader = False if group.is_uploader else True
    else:
        raise BadRequest()

    db.session.commit()
    flash('Usergroup has been updated')

    return redirect(url_for('admin.usergroup'))


@admin.route('/usergroup/<groupid>/rename', methods=['GET', 'POST'])
@login_required
def rename_usergroup(groupid):
    group = Usergroup.query.filter_by(id=groupid).first_or_404()

    form = AdminRenameUsergroupForm()
    form.next.data = url_for('admin.usergroup')

    if request.method == 'GET':
        form.name.data = group.name

    if form.validate_on_submit():
        group.name = form.name.data

        db.session.commit()

        flash('Usergroup name has been updated')
        return form.redirect()

    return render_template('admin/usergroup_rename.html', form=form)


@admin.route('/usergroup/<groupid>/delete', methods=['GET'])
def delete_usergroup(groupid):
    group = Usergroup.query.filter_by(id=groupid).first_or_404()
    if group.users.count() > 0:
        raise BadRequest()
    else:
        db.session.delete(group)
        db.session.commit()

        flash('Usergroup has been removed')
        return redirect(url_for('admin.usergroup'))


@admin.route('/category', methods=['GET', 'POST'])
@login_required
def category():
    broad_categories = BroadCategory.query.all()
    narrow_categories = NarrowCategory.query.all()
    form = AdminAddCategoryForm()
    form.next.data = url_for('admin.category')

    if form.validate_on_submit():
        cat = None
        if form.type.data == 'broad':
            cat = BroadCategory()
        elif form.type.data == 'narrow':
            cat = NarrowCategory()
        else:
            raise BadRequest()
        cat.description = form.description.data if len(form.description.data) > 0 else None
        cat.name = form.name.data

        db.session.add(cat)
        db.session.commit()

        flash('Category has been added')
        return form.redirect()

    return render_template('admin/category.html',
                           broad=broad_categories,
                           narrow=narrow_categories,
                           form=form,
                           title="Category administration")


@admin.route('/category/delete', methods=['GET'])
@login_required
def delete_category():
    _type = request.args.get('type')
    _catid = request.args.get('catid')
    cat = None

    if _type == 'broad':
        cat = BroadCategory.query.filter_by(id=_catid).first_or_404()
    elif _type == 'narrow':
        cat = NarrowCategory.query.filter_by(id=_catid).first_or_404()
    else:
        raise BadRequest()

    if cat.files.count() > 0:
        raise BadRequest()

    db.session.delete(cat)
    db.session.commit()
    flash('Category has been deleted')
    return redirect(url_for('admin.category'))


@admin.route('/category/rename', methods=['GET', 'POST'])
@login_required
def rename_category():
    _type = request.args.get('type')
    _catid = request.args.get('catid')
    cat = None

    if _type == 'broad':
        cat = BroadCategory.query.filter_by(id=_catid).first_or_404()
    elif _type == 'narrow':
        cat = NarrowCategory.query.filter_by(id=_catid).first_or_404()
    else:
        raise BadRequest()

    form = AdminRenameCategoryForm()
    form.next.data = url_for('admin.category')

    if request.method == 'GET':
        form.type = _type
        form.catid = _catid
        form.name.data = cat.name

    if form.validate_on_submit():
        cat.name = form.name.data

        db.session.commit()
        flash('Category name has been updated')
        return form.redirect()

    return render_template('admin/category_rename.html', form=form)



@admin.route('/category/describe', methods=['GET', 'POST'])
def describe_category():
    _type = request.args.get('type')
    _catid = request.args.get('catid')
    cat = None

    if _type == 'broad':
        cat = BroadCategory.query.filter_by(id=_catid).first_or_404()
    elif _type == 'narrow':
        cat = NarrowCategory.query.filter_by(id=_catid).first_or_404()
    else:
        raise BadRequest()

    form = AdminDescribeCategoryForm()
    form.next.data = url_for('admin.category')

    if request.method == 'GET':
        form.type = _type
        form.catid = _catid
        form.description.data = cat.description if cat.description else ''

    if form.validate_on_submit():
        cat.description = form.description.data

        db.session.commit()
        flash('Category description has been updated')
        return form.redirect()

    return render_template('admin/category_describe.html', form=form)

@admin.route('/file/<fileid>/edit', methods=['GET', 'POST'])
@admin.route('/file/<fileid>/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_file(fileid, slug=None):
    form = AdminFileEditForm()
    _file = File.query.filter_by(id=fileid).first_or_404()

    form.broad_category.choices = [(cat.id, cat.name) for cat in BroadCategory.query.order_by('name')]
    form.narrow_category.choices = [(cat.id, cat.name) for cat in NarrowCategory.query.order_by('name')]
    form.fileid = fileid

    if request.method == 'GET':
        form.filename.data = _file.name
        form.description.data = _file.description
        form.version.data = _file.version
        form.broad_category.data = _file.broad_category_id
        form.narrow_category.data = _file.narrow_category_id

    if form.validate_on_submit():

flaskdepot/base/__init__.py
__author__ = 'Gebruiker'

flaskdepot/configs/__init__.py
__author__ = 'Gebruiker'

flaskdepot/file/__init__.py
__author__ = 'Gebruiker'

flaskdepot/search/__init__.py
__author__ = 'Gebruiker'

flaskdepot/templates/file/edit.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'upload' %}

{% block content %}
    <div class="panel clearfix">
        <form method=post action="{{ url_for('file.edit', fileid=fileid) }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ render_field(form.package) }}
            {{ render_field(form.image_1) }}
            {{ render_field(form.image_2) }}
            {{ render_field(form.version) }}
            {{ render_field(form.description) }}
            {{ render_field(form.broad_category) }}
            {{ render_field(form.narrow_category) }}
            <div class="row">
                <div class="large-12 columns">
                    <input type="submit" value="Update" class="button">
                </div>
            </div>
        </form>
        {{ flashes() }}
    </div>
{% endblock %}

flaskdepot/templates/file/file.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, render_info, cat_flashes, format_date %}
{% set activepage = 'file' %}

{% block content %}
    <style>
        .preview-img {
            max-width: {{ config['PREVIEW_MAX_IMGSIZE'][0] }}px;
        }
    </style>
    <div class="panel clearfix">

        <div class="row" id="row-title">
            <div class="large-12 columns">
                <h4><strong>{{ upload.name }}</strong> by {{ upload.author.username }}</h4>
            </div>
        </div>
        {{ cat_flashes() }}
        <div class="row margin-bottom margin-top" id="row-preview">
            {% if upload.preview2_name %}
            <div class="large-6 columns text-center">
                <img src="{{ url_for('file.preview', id=upload.id, number=1) }}" alt="preview image 1" class="preview-img"/>
            </div>
            <div class="large-6 columns">
                <img src="{{ url_for('file.preview', id=upload.id, number=2) }}" alt="preview image 2" class="preview-img"/>
            </div>
            {% else %}
            <div class="large-12 column text-center">
                <img src="{{ url_for('file.preview', id=upload.id, number=1) }}" alt="preview image 1" class="preview-img"/>
            </div>
            {% endif %}
        </div>
        <div class="row margin-bottom margin-top" id="row-info">
            <h5>Details</h5>
            <div class="large-6 column">
                {{ render_info('Author', upload.author.username) }}
                {{ render_info('Uploaded', format_date(upload.created_on)) }}
                {{ render_info('Updated', format_date(upload.updated_on)) }}
                {{ render_info('Version', upload.version or '1.0') }}
            </div>
            <div class="large-6 column">
                {{ render_info('Broad Category', upload.broad_category.name) }}
                {{ render_info('Narrow Category', upload.narrow_category.name) }}
                {{ render_info('Views', upload.num_views) }}
                {{ render_info('Downloads', upload.num_downloads) }}
            </div>
        </div>
        <div class="row margin-bottom margin-top" id="row-download">
            <h5>Download</h5>
            {% if upload.is_locked %}
                <div data-alert class="alert-box alert radius">
                    This file is locked. You cannot download it at this time.
                    <a href="#" class="close">&times;</a>
                </div>
            {%  elif current_user.is_anonymous() %}
                <div data-alert class="alert-box info radius">
                    Sorry, only registered users can download files.
                    <a href="#" class="close">&times;</a>
                </div>
            {% elif upload.is_featured %}
                <a href="{{ url_for('file.package', id=upload.id) }}" class="button success radius">Download Featured File</a>
            {% else %}
                <a href="{{ url_for('file.package', id=upload.id) }}" class="button radius">Download File</a>
            {% endif %}
        </div>
        {% if not current_user.is_anonymous() and (current_user.group.is_admin or current_user == upload.author) %}
        <div class="row margin-bottom margin-top" id="row-tools">
            <h5>Tools</h5>
            <div class="button-bar">
                <ul class="button-group radius" id="author-buttons">
                    {% if current_user.group.is_admin %}
                        <li><a href="{{ url_for('admin.edit_file', fileid=upload.id, slug=upload.slug) }}" class="button small success">Edit File</a></li>
                    {% else %}
                        <li><a href="{{ url_for('file.edit', fileid=upload.id, slug=upload.slug) }}" class="button small success">Edit File</a></li>
                    {% endif %}
                    <li><a href="#" class="button small warning">Lock File</a></li>
                    <li><a href="#" class="button small alert">Delete File</a></li>
                </ul>
                {% if current_user.group.is_admin %}
                <ul class="button-group radius" id="admin-buttons">
                    <li><a href="#" class="button small secondary">Feature File</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
        {% endif %}
        <div class="row margin-bottom margin-top" id="row-description">
            <h5>Description</h5>
            {{ upload.description | safe }}
        </div>
        <div class="row margin-bottom margin-top" id="row-evaluation">
            <h5>Evaluation</h5>
            <fieldset>
                <legend>Current rating</legend>
                    {% if avg_rating %}
                    <p style="margin-bottom: 0">{{ upload.name }} has received an average of <strong>{{ avg_rating }} / 5</strong> points, out of
                       {{ num_rating }} vote(s).</p>
                    {% else %}
                    <p style="margin-bottom: 0">{{ upload.name }} has not received any votes yet.</p>
                    {% endif %}
            </fieldset>
            <fieldset>
                <legend>Rate this file</legend>
                <form method="post" action="{{ url_for('file.file_one', fileid=upload.id) }}">
                    {{ form.hidden_tag() }}
                    {% if allow_rating %}
                        {{ render_field(form.rating, placeholder='Optional (>= 0 and <= 5)') }}
                    {% endif %}
                    {{ render_field(form.comment, placeholder='>= 16 and <= 512 characters') }}
                    <input type="submit" value="evaluate" class="button info small" style="margin-bottom: 0px;">
                </form>
            </fieldset>
        </div>
        <div class="row margin-bottom margin-top" id="row-comments">
            <h5>Comments</h5>
            <table style="min-width: 100%;">
                <thead>
                    <tr>
                        <th style="width:30%;">User</th>
                        <th style="width:70%;">Comment</th>
                    </tr>
                </thead>
                <tbody>
                    {% with comments = upload.comments %}
                        {% for comment in comments|reverse %}
                            <tr>
                                <td>{{ comment.user.username|striptags }}</td>
                                <td>{{ comment.text|striptags }}</td>
                            </tr>
                        {% endfor %}
                    {% endwith %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

flaskdepot/templates/file/upload.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'upload' %}

{% block content %}
    <div class="panel clearfix">
        <form method=post action="{{ url_for('file.upload') }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ render_field(form.filename) }}
            {{ render_field(form.package) }}
            {{ render_field(form.image_1) }}
            {{ render_field(form.image_2) }}
            {{ render_field(form.version) }}
            {{ render_field(form.description) }}
            {{ render_field(form.broad_category) }}
            {{ render_field(form.narrow_category) }}
            <div class="row">
                <div class="large-12 columns">
                    <input type="submit" value="Upload" class="button">
                </div>
            </div>
        </form>
        {{ flashes() }}
    </div>
{% endblock %}