flaskdepot/search/models.py
__author__ = 'Gebruiker'

flaskDepot/views/file.py
import os
from flask.ext.login import current_user, login_required
from sqlalchemy import func
from werkzeug.exceptions import NotAcceptable, abort
from werkzeug.utils import secure_filename
from flask import render_template, flash, url_for
from slugify import slugify
from flaskdepot import app, db
from flaskdepot.controllers.file import UploadForm, EvaluationForm
from flaskdepot.models import File, BroadCategory, NarrowCategory, Comment, Vote


@app.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    form.broad_category.choices = [(cat.id, cat.name) for cat in BroadCategory.query.order_by('name')]
    form.narrow_category.choices = [(cat.id, cat.name) for cat in NarrowCategory.query.order_by('name')]

    if form.validate_on_submit():
        new_file = File()
        new_file.name = form.filename.data
        new_file.slug = slugify(form.filename.data)
        new_file.file_name = secure_filename(form.package.data.filename)
        new_file.preview1_name = secure_filename(form.image_1.data.filename)
        new_file.preview2_name = secure_filename(form.image_2.data.filename) or None
        new_file.description = form.description.data
        new_file.version = form.version.data
        new_file.broad_category_id = form.broad_category.data
        new_file.narrow_category_id = form.narrow_category.data
        new_file.author_id = current_user.id

        package = form.package.data
        package.save(os.path.join(app.config['FILE_DIR'], secure_filename(package.filename)))

        prev1 = form.image_1.data
        prev1.save(os.path.join(app.config['PREVIEW_DIR'], secure_filename(prev1.filename)))

        if len(form.image_2.data.filename) is not 0:
            prev2 = form.image_2.data
            prev2.save(os.path.join(app.config['PREVIEW_DIR'], secure_filename(prev2.filename)))

        db.session.add(new_file)
        db.session.commit()

        flash('File has been uploaded')

    return render_template('upload.html', form=form, title="Upload")


@app.route('/file/<fileid>/<slug>/', methods=['GET', 'POST'])
@app.route('/file/<fileid>/', methods=['GET', 'POST'])
def file_one(fileid, slug=None):
    form = EvaluationForm()

    if form.validate_on_submit():
        if form.comment.data:
            comment = Comment()
            comment.text = form.comment.data
            comment.user_id = current_user.id
            comment.file_id = fileid
            db.session.add(comment)
            db.session.commit()
            flash(u'Your comment has been added', 'success')
    if form.rating.data:
        vote = Vote.query.filter_by(file_id=fileid, user_id=current_user.id).first()
        if not vote:
            vote = Vote()
            vote.value = form.rating.data
            vote.file_id = fileid
            vote.user_id = current_user.id
            db.session.add(vote)
            db.session.commit()
            flash(u'Your rating has been added', 'success')
        else:
            flash(u'You have already voted for this file', 'alert')

    _file = File.query.filter_by(id=fileid).first()

    if not _file:
        abort(404)

    allow_rating = not current_user.is_anonymous() and (Vote.query.filter_by(file_id=fileid, user_id=current_user.id).first() is None)
    num_rating = db.session.query(func.count(Vote.id)).filter_by(file_id=fileid).scalar()
    avg_rating = db.session.query(func.avg(Vote.value)).filter_by(file_id=fileid).scalar()

    return render_template('file.html',
                           upload=_file,
                           form=form,
                           allow_rating=allow_rating,
                           num_rating=num_rating,
                           avg_rating=avg_rating,
                           title=u'{0} by {1}'.format(_file.name, _file.author.username))


@app.route('/file/all/', methods=['GET'])
@login_required
def file_all():
    files = File.query.all()
    ret = ''
    for afile in files:
        ret += u'{0} by {1}<br>'.format(afile.name, afile.author.username)
    return ret

flaskdepot/base/__init__.py
__author__ = 'Gebruiker'

flaskdepot/base/views.py
from flask import Blueprint, render_template
from flaskdepot.file.models import File, Comment

base = Blueprint("base", __name__)


@base.route('/')
@base.route('/index/', methods=['GET'])
def index():
    files = File.query.order_by(File.created_on).limit(3).all()
    comments = Comment.query.order_by(Comment.id).limit(10).all()
    return render_template('index.html', files=files, comments=comments, title='Index')

flaskdepot/configs/__init__.py
__author__ = 'Gebruiker'

flaskdepot/file/__init__.py
__author__ = 'Gebruiker'

flaskdepot/file/views.py
from datetime import datetime
import os
from flask import Blueprint, render_template, flash, abort, send_from_directory, current_app, url_for, request
from flask.ext.login import login_required, current_user
from slugify import slugify
from sqlalchemy import func
from werkzeug.exceptions import NotAcceptable, NotFound, Forbidden
from werkzeug.utils import secure_filename
from flaskdepot.extensions import db
from flaskdepot.file.controllers import UploadForm, EvaluationForm, EditForm
from flaskdepot.file.models import BroadCategory, File, Comment, Vote, Download, NarrowCategory

file = Blueprint("file", __name__)


@file.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    form.broad_category.choices = [(cat.id, cat.name) for cat in BroadCategory.query.order_by('name')]
    form.narrow_category.choices = [(cat.id, cat.name) for cat in NarrowCategory.query.order_by('name')]
    form.next.data = url_for('base.index')

    if form.validate_on_submit():
        new_file = File()
        new_file.name = form.filename.data
        new_file.slug = slugify(form.filename.data)
        new_file.file_name = secure_filename(form.package.data.filename)
        new_file.preview1_name = secure_filename(form.image_1.data.filename)
        new_file.preview2_name = secure_filename(form.image_2.data.filename) or None
        new_file.description = form.description.data
        new_file.version = form.version.data
        new_file.broad_category_id = form.broad_category.data
        new_file.narrow_category_id = form.narrow_category.data
        new_file.author_id = current_user.id

        # Create subdirectories for images and previews based on slug
        file_subdir = os.path.join(current_app.config['FILE_DIR'], new_file.slug)
        image_subdir = os.path.join(current_app.config['PREVIEW_DIR'], new_file.slug)
        if not os.path.exists(file_subdir):
            os.makedirs(file_subdir)
        if not os.path.exists(image_subdir):
            os.makedirs(image_subdir)

        form.package.data.save(os.path.join(file_subdir, new_file.file_name))

        prev1 = form.image_1.data
        prev1.save(os.path.join(image_subdir, new_file.preview1_name))

        if len(form.image_2.data.filename) is not 0:
            prev2 = form.image_2.data
            prev2.save(os.path.join(image_subdir, new_file.preview2_name))

        db.session.add(new_file)
        db.session.commit()

        flash('File has been uploaded')
        return form.redirect()

    return render_template('file/upload.html', form=form, title="Upload")


@file.route('/<fileid>/edit/', methods=['GET', 'POST'])
@file.route('/<fileid>/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit(fileid, slug=None):
    form = EditForm()
    _file = File.query.filter_by(id=fileid).first_or_404()

    if _file.author.id == current_user.id:
        form.next.data = url_for('.file_one', fileid=fileid)
        form.broad_category.choices = [(cat.id, cat.name) for cat in BroadCategory.query.order_by('name')]
        form.narrow_category.choices = [(cat.id, cat.name) for cat in NarrowCategory.query.order_by('name')]

        if request.method == 'GET':
            form.description.data = _file.description
            form.version.data = _file.version
            form.broad_category.data = _file.broad_category_id
            form.narrow_category.data = _file.narrow_category_id

        if form.validate_on_submit():
            _file.description = form.description.data
            _file.version = form.version.data
            _file.broad_category_id = form.broad_category.data
            _file.narrow_category_id = form.narrow_category.data

            file_subdir = os.path.join(current_app.config['FILE_DIR'], _file.slug)
            image_subdir = os.path.join(current_app.config['PREVIEW_DIR'], _file.slug)

            # Slug did not change, so save in the existing directory
            if len(form.package.data.filename) > 0:
                _file.file_name = secure_filename(form.package.data.filename)
                form.package.data.save(os.path.join(file_subdir, _file.file_name))
            if len(form.image_1.data.filename) > 0:
                _file.preview1_name = secure_filename(form.image_1.data.filename)
                form.image_1.data.save(os.path.join(image_subdir, _file.preview1_name))
            if len(form.image_2.data.filename) > 0:
                _file.preview2_name = secure_filename(form.image_2.data.filename)
                form.image_2.data.save(os.path.join(image_subdir, _file.preview2_name))

            db.session.commit()

            flash('File has been updated')
            form.redirect()

        return render_template('file/edit.html', form=form, fileid=fileid, title="Edit file")
    else:
        raise Forbidden()


@file.route('/<fileid>/<slug>/', methods=['GET', 'POST'])
@file.route('/<fileid>/', methods=['GET', 'POST'])
def file_one(fileid, slug=None):
    form = EvaluationForm()

    if form.validate_on_submit():
        if form.comment.data:
            comment = Comment()
            comment.text = form.comment.data
            comment.user_id = current_user.id
            comment.file_id = fileid
            db.session.add(comment)
            db.session.commit()
            flash(u'Your comment has been added', 'success')
    if form.rating.data:
        vote = Vote.query.filter_by(file_id=fileid, user_id=current_user.id).first()
        if not vote:
            vote = Vote()
            vote.value = form.rating.data
            vote.file_id = fileid
            vote.user_id = current_user.id
            db.session.add(vote)
            db.session.commit()
            flash(u'Your rating has been added', 'success')
        else:
            flash(u'You have already voted for this file', 'alert')

    _file = File.query.filter_by(id=fileid).first()

    if not _file:
        abort(404)

    allow_rating = not current_user.is_anonymous() and (Vote.query.filter_by(file_id=fileid, user_id=current_user.id).first() is None)
    num_rating = db.session.query(func.count(Vote.id)).filter_by(file_id=fileid).scalar()
    avg_rating = db.session.query(func.avg(Vote.value)).filter_by(file_id=fileid).scalar()

    return render_template('file/file.html',
                           upload=_file,
                           form=form,
                           allow_rating=allow_rating,
                           num_rating=num_rating,
                           avg_rating=avg_rating,
                           title=u'{0} by {1}'.format(_file.name, _file.author.username))


@file.route('/all/', methods=['GET'])
@login_required
def file_all():
    files = File.query.all()
    ret = ''
    for _file in files:
        ret += u'{0} by {1}<br>'.format(_file.name, _file.author.username)
    return ret


@file.route('/preview/<id>/<number>/')
@file.route('/preview/<id>/<slug>/<number>')
def preview(id, number, slug=None):
    _file = File.query.filter_by(id=id).first()
    if _file:
        if int(number) == 1:
            if _file.preview1_name:
                return send_from_directory(os.path.join(current_app.config['PREVIEW_DIR'], _file.slug),
                                           _file.preview1_name)
            else:
                raise NotFound()
        elif int(number) == 2:
            if _file.preview2_name:
                return send_from_directory(os.path.join(current_app.config['PREVIEW_DIR'], _file.slug),
                                           _file.preview2_name)
            else:
                raise NotAcceptable()
        else:
            raise NotAcceptable()
    else:
        raise NotFound()


@login_required
@file.route('/package/<id>/')
@file.route('/package/<id>/<slug>')
def package(id, slug=None):
    _file = File.query.filter_by(id=id).first()
    if _file:
        download = Download.query.filter_by(file_id=id, user_id=current_user.id).first()
        if download:
            download.last_downloaded = datetime.utcnow()
            download.num_downloaded += 1
            db.session.commit()
        else:
            download = Download()
            download.file = _file
            download.user = current_user
            download.num_downloaded = 1
            download.last_downloaded = datetime.utcnow()
            db.session.add(download)
            db.session.commit()

        return send_from_directory(os.path.join(current_app.config['FILE_DIR'], _file.slug),
                                   _file.file_name,
                                   as_attachment=True)
    else:
        raise NotFound()

flaskdepot/search/__init__.py
__author__ = 'Gebruiker'

flaskdepot/user/views.py
import datetime
from flask import render_template, request, flash, url_for, redirect, Blueprint, abort
from flask_login import login_user, login_required, current_user, logout_user
from flaskdepot.extensions import db
from flaskdepot.user.models import User, Usergroup
from flaskdepot.user.controllers import RegistrationForm, LoginForm, AccountEditForm, AccountDeleteForm

user = Blueprint("user", __name__)


@user.route('/register/', methods=['GET', 'POST'])
def register():

    if current_user.is_authenticated():
        return redirect(url_for('base.index'))

    form = RegistrationForm()
    form.next.data = url_for('base.index')

    if form.validate_on_submit():
        user = User()
        user.username = form.username.data
        user.set_password(form.password.data)
        user.email = form.email.data
        user.created_ip = request.remote_addr
        user.group = Usergroup.query.filter_by(is_default=True).first()

        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash(u'Thank you for signing up! You are now logged in as {0}'.format(user.username))

        return form.redirect()
    else:
        return render_template('user/register.html', form=form, title=u'Registration')


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    form.next.data = url_for('base.index')

    if form.validate_on_submit():
        if not form.remember.data:
            login_user(form.user)
            form.user.last_active_ip = request.remote_addr
            form.user.last_active_on = datetime.datetime.now()
            db.session.commit()
        else:
            login_user(form.user, remember=form.remember.data)

        flash(u'You have been logged in as {0}'.format(form.user.username))
        return form.redirect()
    else:
        return render_template('user/login.html', form=form, title=u'Log in')


@user.route('/logout/', methods=['GET'])
@login_required
def logout():
    logout_user()
    flash(u'You have been logged out')
    return redirect(url_for('base.index'))


# User Profile
@user.route('/<id>/', methods=['GET'])
@login_required
def user_one(id):
    if current_user.group.is_admin or current_user.id == int(id):
        _user = User.query.filter_by(id=id).first()
        return render_template('user/profile.html', user=_user, title=u"Profile for {0}".format(_user.username))
    else:
        return 'You cannot access this page'


@user.route('/<id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_user(id):
    if current_user.group.is_admin or current_user.id == int(id):
        _user = User.query.filter_by(id=id).first()
        form = AccountEditForm()

        if form.validate_on_submit():
            if form.email.data:
                _user.email = form.email.data
                flash('The e-mail address has been updated')
            if form.password.data and (form.password.data == form.confirm_password.data):
                _user.set_password(form.password.data)
                flash('The password has been updated')
            db.session.commit()

        return render_template('user/edit.html', form=form, title=u"Edit profile for {0}".format(_user.username), user=_user)
    else:
        abort(403)


@user.route('/<id>/delete/', methods=['GET', 'POST'])
@login_required
def delete_user(id):
    if not current_user.group.is_admin:
        abort(403)
    else:
        _user = User.query.filter_by(id=id).first()
        form = AccountDeleteForm()
        form.next.data = url_for('.user_one', id=id)

        if form.validate_on_submit():
            if _user.username == form.username.data:
                _user.active = False
                db.session.commit()
            else:
                form.username.errors.append('Please enter the correct username')
                form.redirect()
        else:
            return render_template('user/delete.html', form=form,
                                   title=u"Delete account for {0}".format(_user.username), user=_user)


@user.route('/me/', methods=['GET'])
@login_required
def user_me():
    return redirect(url_for('user.user_one', id=current_user.id))

flaskdepot/templates/admin_user_edit.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'upload' %}

{% block content %}
    <div class="panel clearfix">
        <form method="post">
            {{ form.hidden_tag() }}
            {{ render_field(form.username, placeholder=user.username) }}
            {{ render_field(form.group) }}
            <div class="row">
                <div class="large-12 columns">
                    <input type="submit" value="Edit" class="button">
                </div>
            </div>
        </form>
        {{ flashes() }}
    </div>
{% endblock %}

flaskdepot/templates/error.html
{% extends "layout.html" %}
{% set title = name %}

{% block content %}
    <div class="panel clearfix">
        <h4>{{ name }}</h4>
        <p>{{ message }}</p>
    </div>
{% endblock %}

flaskdepot/templates/file.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, render_info, cat_flashes, format_date %}
{% set activepage = 'file' %}

{% block content %}
    <style>
        .preview-img {
            max-width: {{ config['PREVIEW_MAX_IMGSIZE'][0] }}px;
        }
    </style>
    <div class="panel clearfix">

        <div class="row" id="row-title">
            <div class="large-12 columns">
                <h4><strong>{{ upload.name }}</strong> by {{ upload.author.username }}</h4>
            </div>
        </div>
        {{ cat_flashes() }}
        <div class="row margin-bottom margin-top" id="row-preview">
            {% if upload.preview2_name %}
            <div class="large-6 columns text-center">
                <img src="{{ url_for('file.preview', id=upload.id, number=1) }}" alt="preview image 1" class="preview-img"/>
            </div>
            <div class="large-6 columns">
                <img src="{{ url_for('file.preview', id=upload.id, number=2) }}" alt="preview image 2" class="preview-img"/>
            </div>
            {% else %}
            <div class="large-12 column text-center">
                <img src="{{ url_for('file.preview', id=upload.id, number=1) }}" alt="preview image 1" class="preview-img"/>
            </div>
            {% endif %}
        </div>
        <div class="row margin-bottom margin-top" id="row-info">
            <h5>Details</h5>
            <div class="large-6 column">
                {{ render_info('Author', upload.author.username) }}
                {{ render_info('Uploaded', format_date(upload.created_on)) }}
                {{ render_info('Updated', format_date(upload.updated_on)) }}
                {{ render_info('Version', upload.version or '1.0') }}
            </div>
            <div class="large-6 column">
                {{ render_info('Broad Category', upload.broad_category.name) }}
                {{ render_info('Narrow Category', upload.narrow_category.name) }}
                {{ render_info('Views', upload.num_views) }}
                {{ render_info('Views', upload.num_downloads) }}
            </div>
        </div>
        <div class="row margin-bottom margin-top" id="row-download">
            <h5>Download</h5>
            {% if upload.is_locked %}
                <div data-alert class="alert-box alert radius">
                    This file is locked. You cannot download it at this time.
                    <a href="#" class="close">&times;</a>
                </div>
            {%  elif current_user.is_anonymous() %}
                <div data-alert class="alert-box info radius">
                    Sorry, only registered users can download files.
                    <a href="#" class="close">&times;</a>
                </div>
            {% elif upload.is_featured %}
                <a href="{{ url_for('file.package', id=upload.id) }}" class="button success radius">Download Featured File</a>
            {% else %}
                <a href="{{ url_for('file.package', id=upload.id) }}" class="button radius">Download File</a>
            {% endif %}
        </div>
        {% if not current_user.is_anonymous() and (current_user.group.is_admin or current_user == upload.author) %}
        <div class="row margin-bottom margin-top" id="row-tools">
            <h5>Tools</h5>
            <div class="button-bar">
                <ul class="button-group radius" id="author-buttons">
                    <li><a href="#" class="button small success">Edit File</a></li>
                    <li><a href="#" class="button small warning">Lock File</a></li>
                    <li><a href="#" class="button small alert">Delete File</a></li>
                </ul>
                {% if current_user.group.is_admin %}
                <ul class="button-group radius" id="admin-buttons">
                    <li><a href="#" class="button small secondary">Feature File</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
        {% endif %}
        <div class="row margin-bottom margin-top" id="row-description">
            <h5>Description</h5>
            {{ upload.description | safe }}
        </div>
        <div class="row margin-bottom margin-top" id="row-evaluation">
            <h5>Evaluation</h5>
            <fieldset>
                <legend>Current rating</legend>
                    {% if avg_rating %}
                    <p style="margin-bottom: 0px">{{ upload.name }} has received an average of <strong>{{ avg_rating }} / 5</strong> points, out of
                       {{ num_rating }} vote(s).</p>
                    {% else %}
                    <p style="margin-bottom: 0px">{{ upload.name }} has not received any votes yet.</p>
                    {% endif %}
            </fieldset>
            <fieldset>
                <legend>Rate this file</legend>
                <form method="post" action="{{ url_for('file.file_one', fileid=upload.id) }}">
                    {{ form.hidden_tag() }}
                    {% if allow_rating %}
                        {{ render_field(form.rating, placeholder='Optional (>= 0 and <= 5)') }}
                    {% endif %}
                    {{ render_field(form.comment, placeholder='>= 16 and <= 512 characters') }}
                    <input type="submit" value="evaluate" class="button info small" style="margin-bottom: 0px;">
                </form>
            </fieldset>
        </div>
        <div class="row margin-bottom margin-top" id="row-comments">
            <h5>Comments</h5>
            <table style="min-width: 100%;">
                <thead>
                    <tr>
                        <th style="width:30%;">User</th>
                        <th style="width:70%;">Comment</th>
                    </tr>
                </thead>
                <tbody>
                    {% with comments = upload.comments %}
                        {% for comment in comments|reverse %}
                            <tr>
                                <td>{{ comment.user.username|striptags }}</td>
                                <td>{{ comment.text|striptags }}</td>
                            </tr>
                        {% endfor %}
                    {% endwith %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

flaskdepot/templates/index.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'index' %}

{% block content %}
    <div class="panel clearfix">
        <p>{{ flashes() }}</p>
        <div class="row margin-bottom" id="row-files">
            <h3>Latest uploads</h3>
            {% if files|length < 1 %}
                <div class="large-3 large-centered">
                    <em>No files have been uploaded yet</em>
                </div>
            {% else %}
                <ul class="large-block-grid-{{ files|length }} large-centered">
                    {% for file in files|reverse %}
                        <li>
                            <div class="row">
                                <strong><a href="{{ url_for('file.file_one', fileid=file.id, slug=file.slug) }}">{{ file.name }}</a></strong>
                            </div>
                            <div class="row">
                                <img src="{{ url_for('file.preview', id=file.id, number=1) }}" alt="preview image 1" class="preview-img" style="width: {{ config['PREVIEW_MAX_IMGSIZE'][0] }}px"/>
                            </div>
                            <div class="row">
                                <div class="large-12">
                                    created by <strong>{{ file.author.username }}</strong>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="row margin-bottom" id="row-comments">
            <h3>Latest comments</h3>
            {% if comments|length < 1 %}
                <div class="large-9 large-centered">
                    <em>No comments have been made yet</em>
                </div>
            {% else %}
                <table style="min-width: 100%;">
                    <thead>
                    <tr>
                        <th style="width:30%;">User</th>
                        <th style="width:70%;">Comment</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for comment in comments|reverse %}
                            <tr>
                                <td>{{ comment.user.username|striptags }}</td>
                                <td>{{ comment.text|striptags }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

flaskdepot/templates/layout.html
{% set active_page = active_page|default('index') -%}
{% from "_helpers.html" import render_nav %}

<!doctype html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="index,follow,noodp,noydir"/>

        <link href="{{ url_for('static', filename='css/normalize.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ url_for('static', filename='css/foundation.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ url_for('static', filename='css/foundation-icons.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet" type="text/css">

        <script src="{{ url_for('static', filename='js/vendor/modernizr.js') }}"></script>

        <title>{% block title %}{{ title }}{% endblock %} - {{ config['DEPOT_TITLE'] }}</title>
    {% endblock %}
</head>
<body>
    {% block navbar %}
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name"><h1><a href="{{ url_for('base.index') }}">{{ config['DEPOT_TITLE'] }}</a></h1></li>
                <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
            </ul>
            <section class="top-bar-section">
                <ul class="right">
                    {% if current_user.is_authenticated() %}
                        <li class="has-form">
                            <a href="{{ url_for('user.logout') }}" class="button">Log out</a>
                        </li>
                    {% else %}
                        <li class="has-form">
                            <a href="{{ url_for('user.register') }}" class="button">Register</a>
                        </li>
                        <li class="has-form">
                            <a href="{{ url_for('user.login') }}" class="button">Log in</a>
                        </li>
                    {% endif %}
                </ul>

                <ul class="left">
                    {{ render_nav('base.index', 'index', 'Index', active_page) }}
                    {{ render_nav('search.index', 'search_index', 'Search', active_page) }}
                    {% if current_user.is_authenticated() %}
                        {% if current_user.group.is_admin %}
                            {{ render_nav('admin.index', 'admin_index', 'Administration', active_page) }}
                        {% endif %}
                        {% if current_user.group.is_uploader %}
                            {{ render_nav('file.upload', 'upload', 'Upload File', active_page) }}
                        {% endif %}
                        {{ render_nav('user.user_me', 'profile', 'Profile', active_page) }}
                    {% endif %}
                </ul>
            </section>
        </nav>
    {% endblock %}

    {% block content %}{% endblock %}

    {% block foot %}
        <script src="{{ url_for('static', filename='js/vendor/jquery.js') }}" type="text/javascript"></script>
        <script src="{{ url_for('static', filename='js/foundation.min.js') }}" type="text/javascript"></script>

        <script type="text/javascript">
            $(document).foundation();
        </script>
    {% endblock %}
</body>
</html>

flaskdepot/templates/user_edit.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_field, flashes %}
{% set activepage = 'upload' %}

{% block content %}
    <div class="panel clearfix">
        <form method="post">
            {{ form.hidden_tag() }}
            {{ render_field(form.email, placeholder=user.email) }}
            {{ render_field(form.password) }}
            {{ render_field(form.confirm_password) }}
            <div class="row">
                <div class="large-12 columns">
                    <input type="submit" value="Edit" class="button">
                </div>
            </div>
        </form>
        {{ flashes() }}
    </div>
{% endblock %}